[package]
name = "graft-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "graft"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.57", features = ["derive"] }
git2 = "0.20.4"
